spring.application.name=Bitcoin
spring.data.mongodb.uri=mongodb+srv://shalvi_gour:shalvi123@cluster0.prlh422.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=bitcoin
spring.data.mongodb.auto-index-creation=true

server.port=8081
server.servlet.context-path=/bitcoin

spring.data.redis.host=redis-16568.c261.us-east-1-4.ec2.cloud.redislabs.com
spring.data.redis.port=16568
spring.data.redis.password=yvz9niztIC3ih7QfjhoRxvCPyRlt5o5O

# Connection pool settings (Good for performance)
spring.data.redis.lettuce.pool.max-active=8