spring.application.name=Bitcoin
spring.data.mongodb.uri=mongodb+srv://shalvi_gour:shalvi123@cluster0.prlh422.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=bitcoin
spring.data.mongodb.auto-index-creation=true

server.port=8081
server.servlet.context-path=/bitcoin